version: 2

models:
  - name: stg_table1
    columns:
      - name: pkid
        data_tests:
          - not_null
          - unique
      - name: str1
        data_tests:                  
          - no_blank_or_stray_str:
              config:
               severity: warn
               store_failures: true

      - name: num1
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
              config:
                severity: warn
                store_failures: true
              

  - name: stg_table2
    columns:
      - name: pkid
        data_tests:
          - not_null
          - unique
      - name: str1
        data_tests:                  
          - no_blank_or_stray_str:
              config:
               severity: warn   
               store_failures: true

      - name: date1
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: "'2000-01-01'"
                max_value: "current_date()"
              config:
                severity: warn
                store_failures: true